version: 2
jobs:
 build:
   machine: true
   steps:
     - checkout
     # login to docker hub
     - run: docker login -u $DOCKER_USER -p $DOCKER_PASS
     # build the docker image
     - run: docker build -t $DOCKER_USER/py-essential:$CIRCLE_BRANCH .
     # deploy the docker image
     - run: docker push $DOCKER_USER/py-essential:$CIRCLE_BRANCH